#include <inttypes.h>

typedef unsigned __int128 uint128_t;

void store_prod(uint128_t* dest, uint64_t x, uint64_t y)
{
    *dest = x * (uint128_t) y;
}

// Additionally, the x86-64 instruction set includes two different “one-operand”
// multiply instructions to compute the full 128-bit product of two 64-bit values—
// one for unsigned (mulq) and one for two’s-complement (imulq) multiplication.
// For both of these instructions, one argument must be in register %rax, and the
// other is given as the instruction source operand. The product is then stored in
// registers %rdx (high-order 64 bits) and %rax (low-order 64 bits)

// ASM code generated by gcc
//
// store_prod:
// dest in %rdi, x in %rsi, y in %rdx
// 	endbr64
// 	movq	%rsi, %rax        copy x to multiplicand (one of the argument must be in register %rax)
// 	mulq	%rdx              multiply by y
// 	movq	%rax, (%rdi)      store lower 8 bytes at dest
// 	movq	%rdx, 8(%rdi)     store upper 8 bytes at dest+8
// 	ret